name: Cleanup Pages Artifacts

on:
  schedule:
    - cron: '30 3 * * 0'
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old Deploy GitHub Pages workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          workflow: deploy-pages.yml
          retain_days: 14
          keep_minimum_runs: 8
